sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2.2'
before_install:
  - npm i -g npm@^2.0.0
  - git config --global user.email "test@test.com"
  - git config --global user.name "Test Tester"
before_script:
  - npm prune
script:
  - npm test
  - npm run e2e
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
